<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Tests\Api\Infrastructure\DesignTime;

use Automattic\WooCommerce\Api\Infrastructure\DesignTime\StalenessChecker;
use WC_Unit_Test_Case;

/**
 * Tests for {@see StalenessChecker} — the hash-based staleness detector used
 * by `check-api-staleness.php` to decide whether the autogenerated GraphQL
 * API code matches the current code-API sources.
 */
class StalenessCheckerTest extends WC_Unit_Test_Case {
	/**
	 * Temporary directory standing in for a code-API source tree.
	 *
	 * @var string
	 */
	private string $api_dir;

	/**
	 * Temporary directory standing in for the generated output tree.
	 *
	 * @var string
	 */
	private string $autogen_dir;

	/**
	 * Set up: a source tree with two PHP files, one nested.
	 */
	public function setUp(): void {
		parent::setUp();
		$base              = sys_get_temp_dir() . '/staleness-checker-' . uniqid( '', true );
		$this->api_dir     = $base . '/Api';
		$this->autogen_dir = $base . '/Autogenerated';
		mkdir( $this->api_dir, 0777, true );
		mkdir( $this->autogen_dir, 0777, true );
		file_put_contents( $this->api_dir . '/Widget.php', "<?php\nclass Widget {}\n" );
		mkdir( $this->api_dir . '/Sub' );
		file_put_contents( $this->api_dir . '/Sub/Nested.php', "<?php\nclass Nested {}\n" );
	}

	/**
	 * Tear down: remove the temporary trees.
	 */
	public function tearDown(): void {
		$this->rmdir_recursive( dirname( $this->api_dir ) );
		parent::tearDown();
	}

	/**
	 * @testdox is_stale returns true when the hash file is missing.
	 */
	public function test_is_stale_returns_true_when_hash_file_is_missing(): void {
		$this->assertTrue( StalenessChecker::is_stale( $this->api_dir, $this->autogen_dir ) );
	}

	/**
	 * @testdox is_stale returns false when the stored hash matches the current sources.
	 */
	public function test_is_stale_returns_false_when_stored_hash_matches_current_sources(): void {
		$this->write_hash_file( StalenessChecker::compute_source_hash( $this->api_dir ) );
		$this->assertFalse( StalenessChecker::is_stale( $this->api_dir, $this->autogen_dir ) );
	}

	/**
	 * @testdox is_stale returns true when a source file was modified after the hash was recorded.
	 */
	public function test_is_stale_returns_true_when_a_source_file_was_modified_after_the_hash_was_recorded(): void {
		$this->write_hash_file( StalenessChecker::compute_source_hash( $this->api_dir ) );
		file_put_contents( $this->api_dir . '/Widget.php', "<?php\nclass Widget { public int \$x = 1; }\n" );
		$this->assertTrue( StalenessChecker::is_stale( $this->api_dir, $this->autogen_dir ) );
	}

	/**
	 * @testdox is_stale returns true when a source file was renamed.
	 */
	public function test_is_stale_returns_true_when_a_source_file_was_renamed(): void {
		$this->write_hash_file( StalenessChecker::compute_source_hash( $this->api_dir ) );
		rename( $this->api_dir . '/Widget.php', $this->api_dir . '/Gadget.php' );
		$this->assertTrue( StalenessChecker::is_stale( $this->api_dir, $this->autogen_dir ) );
	}

	/**
	 * @testdox is_stale returns true when a source file was added.
	 */
	public function test_is_stale_returns_true_when_a_source_file_was_added(): void {
		$this->write_hash_file( StalenessChecker::compute_source_hash( $this->api_dir ) );
		file_put_contents( $this->api_dir . '/NewClass.php', "<?php\nclass NewClass {}\n" );
		$this->assertTrue( StalenessChecker::is_stale( $this->api_dir, $this->autogen_dir ) );
	}

	/**
	 * @testdox is_stale ignores non-PHP files.
	 */
	public function test_is_stale_ignores_non_php_files(): void {
		$this->write_hash_file( StalenessChecker::compute_source_hash( $this->api_dir ) );
		file_put_contents( $this->api_dir . '/README.md', 'docs' );
		$this->assertFalse( StalenessChecker::is_stale( $this->api_dir, $this->autogen_dir ) );
	}

	/**
	 * @testdox compute_source_hash is stable across runs.
	 */
	public function test_compute_source_hash_is_stable_across_runs(): void {
		$first  = StalenessChecker::compute_source_hash( $this->api_dir );
		$second = StalenessChecker::compute_source_hash( $this->api_dir );
		$this->assertSame( $first, $second );
	}

	/**
	 * Record a hash as if a build had just run.
	 *
	 * @param string $hash The hash to store.
	 */
	private function write_hash_file( string $hash ): void {
		file_put_contents( $this->autogen_dir . '/api_source_hash.txt', $hash );
	}

	/**
	 * Delete a directory and everything below it.
	 *
	 * @param string $dir Absolute path of the directory.
	 */
	private function rmdir_recursive( string $dir ): void {
		if ( ! is_dir( $dir ) ) {
			return;
		}
		$iterator = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( $dir, \FilesystemIterator::SKIP_DOTS ),
			\RecursiveIteratorIterator::CHILD_FIRST
		);
		foreach ( $iterator as $file ) {
			$file->isDir() ? rmdir( $file->getPathname() ) : unlink( $file->getPathname() );
		}
		rmdir( $dir );
	}
}
