<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Tests\Internal\Api;

use Automattic\WooCommerce\Api\Infrastructure\Main;
use Automattic\WooCommerce\Internal\Api\GraphQLEndpointRegistrar;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLController as DummyGraphQLController;
use WC_REST_Unit_Test_Case;

/**
 * Tests for {@see GraphQLEndpointRegistrar} — the deferred-registration helper
 * used by plugins via {@see Main::register_graphql_endpoint()}.
 */
class GraphQLEndpointRegistrarTest extends WC_REST_Unit_Test_Case {
	/**
	 * Tear down.
	 */
	public function tearDown(): void {
		delete_option( Main::OPTION_GET_ENDPOINT_ENABLED );
		parent::tearDown();
	}

	/**
	 * @testdox handle_rest_api_init registers a route with the configured methods.
	 */
	public function test_handle_rest_api_init_registers_route_with_methods(): void {
		update_option( Main::OPTION_GET_ENDPOINT_ENABLED, 'yes' );

		$registrar = new GraphQLEndpointRegistrar(
			DummyGraphQLController::class,
			'wc-test',
			'/registrar-route',
			array( 'GET', 'POST' )
		);

		$registrar->handle_rest_api_init();

		$routes = rest_get_server()->get_routes();
		$this->assertArrayHasKey( '/wc-test/registrar-route', $routes );
		$methods = $routes['/wc-test/registrar-route'][0]['methods'];
		$this->assertTrue( $methods['GET'] ?? false );
		$this->assertTrue( $methods['POST'] ?? false );
	}

	/**
	 * @testdox handle_rest_api_init applies the GET-endpoint setting.
	 */
	public function test_handle_rest_api_init_strips_get_when_setting_is_off(): void {
		update_option( Main::OPTION_GET_ENDPOINT_ENABLED, 'no' );

		$registrar = new GraphQLEndpointRegistrar(
			DummyGraphQLController::class,
			'wc-test',
			'/post-only-route',
			array( 'GET', 'POST' )
		);

		$registrar->handle_rest_api_init();

		$routes = rest_get_server()->get_routes();
		$this->assertArrayHasKey( '/wc-test/post-only-route', $routes );
		$methods = $routes['/wc-test/post-only-route'][0]['methods'];
		$this->assertTrue( $methods['POST'] ?? false );
		$this->assertFalse( $methods['GET'] ?? false );
	}

	/**
	 * @testdox handle_rest_api_init skips registration when settings reduce the methods to none.
	 */
	public function test_handle_rest_api_init_skips_registration_when_no_methods_remain(): void {
		update_option( Main::OPTION_GET_ENDPOINT_ENABLED, 'no' );

		$registrar = new GraphQLEndpointRegistrar(
			DummyGraphQLController::class,
			'wc-test',
			'/get-only-route',
			array( 'GET' )
		);

		$registrar->handle_rest_api_init();

		$routes = rest_get_server()->get_routes();
		$this->assertArrayNotHasKey( '/wc-test/get-only-route', $routes );
	}

	/**
	 * @testdox the registered route uses `__return_true` as its permission_callback, since authorization happens per operation.
	 */
	public function test_registered_route_uses_return_true_permission_callback(): void {
		$registrar = new GraphQLEndpointRegistrar(
			DummyGraphQLController::class,
			'wc-test',
			'/permission-route',
			array( 'POST' )
		);

		$registrar->handle_rest_api_init();

		$routes = rest_get_server()->get_routes();
		$this->assertArrayHasKey( '/wc-test/permission-route', $routes );
		$this->assertSame( '__return_true', $routes['/wc-test/permission-route'][0]['permission_callback'] );
	}
}
