<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Tests\Internal\Api;

use Automattic\WooCommerce\Api\Infrastructure\GraphQLControllerBase;
use Automattic\WooCommerce\Api\Infrastructure\Main;
use Automattic\WooCommerce\Internal\Api\OpcacheFileExpiry;
use Automattic\WooCommerce\Tests\Internal\Api\Fixtures\DummyApiAutogenerated\GraphQLController as DummyGraphQLController;
use WC_Unit_Test_Case;

/**
 * Tests for {@see Main} — the entry point that exposes the GET-endpoint
 * setting, bootstraps the engine's hooks, and validates plugin-supplied
 * controller arguments.
 */
class MainTest extends WC_Unit_Test_Case {
	/**
	 * Tear down.
	 */
	public function tearDown(): void {
		delete_option( Main::OPTION_GET_ENDPOINT_ENABLED );
		delete_option( Main::OPTION_ANONYMOUS_REQUESTS_ALLOWED );
		parent::tearDown();
	}

	/**
	 * @testdox are_anonymous_requests_allowed defaults to true when the option is absent.
	 */
	public function test_are_anonymous_requests_allowed_defaults_to_true(): void {
		delete_option( Main::OPTION_ANONYMOUS_REQUESTS_ALLOWED );
		$this->assertTrue( Main::are_anonymous_requests_allowed() );
	}

	/**
	 * @testdox are_anonymous_requests_allowed honours the stored option value.
	 */
	public function test_are_anonymous_requests_allowed_reads_the_option(): void {
		update_option( Main::OPTION_ANONYMOUS_REQUESTS_ALLOWED, 'no' );
		$this->assertFalse( Main::are_anonymous_requests_allowed() );

		update_option( Main::OPTION_ANONYMOUS_REQUESTS_ALLOWED, 'yes' );
		$this->assertTrue( Main::are_anonymous_requests_allowed() );
	}

	/**
	 * @testdox is_get_endpoint_enabled defaults to true when the option is absent.
	 */
	public function test_is_get_endpoint_enabled_defaults_to_true(): void {
		delete_option( Main::OPTION_GET_ENDPOINT_ENABLED );
		$this->assertTrue( Main::is_get_endpoint_enabled() );
	}

	/**
	 * @testdox is_get_endpoint_enabled honours the stored option value.
	 */
	public function test_is_get_endpoint_enabled_reads_the_option(): void {
		update_option( Main::OPTION_GET_ENDPOINT_ENABLED, 'no' );
		$this->assertFalse( Main::is_get_endpoint_enabled() );

		update_option( Main::OPTION_GET_ENDPOINT_ENABLED, 'yes' );
		$this->assertTrue( Main::is_get_endpoint_enabled() );
	}

	/**
	 * @testdox filter_methods_against_settings strips GET when the option is disabled.
	 */
	public function test_filter_methods_strips_get_when_disabled(): void {
		update_option( Main::OPTION_GET_ENDPOINT_ENABLED, 'no' );
		$filtered = Main::filter_methods_against_settings( array( 'GET', 'POST' ) );
		$this->assertSame( array( 'POST' ), $filtered );
	}

	/**
	 * @testdox filter_methods_against_settings keeps GET when the option is enabled.
	 */
	public function test_filter_methods_keeps_get_when_enabled(): void {
		update_option( Main::OPTION_GET_ENDPOINT_ENABLED, 'yes' );
		$filtered = Main::filter_methods_against_settings( array( 'GET', 'POST' ) );
		$this->assertSame( array( 'GET', 'POST' ), $filtered );
	}

	/**
	 * @testdox filter_methods_against_settings can leave the list empty when GET is the only entry and the option is off.
	 */
	public function test_filter_methods_can_return_empty_array(): void {
		update_option( Main::OPTION_GET_ENDPOINT_ENABLED, 'no' );
		$this->assertSame( array(), Main::filter_methods_against_settings( array( 'GET' ) ) );
	}

	/**
	 * @testdox is_enabled returns true, since the plugin only ever loads on PHP 8.1+ and there is no feature flag.
	 */
	public function test_is_enabled(): void {
		$this->assertTrue( Main::is_enabled() );
	}

	/**
	 * @testdox instantiate_graphql_controller throws when the class is not a controller subclass.
	 */
	public function test_instantiate_rejects_unrelated_classes(): void {
		$this->expectException( \InvalidArgumentException::class );
		Main::instantiate_graphql_controller( \stdClass::class );
	}

	/**
	 * @testdox instantiate_graphql_controller throws when the class does not exist.
	 */
	public function test_instantiate_rejects_missing_classes(): void {
		$this->expectException( \InvalidArgumentException::class );
		Main::instantiate_graphql_controller( 'Definitely\\Not\\A\\Class' );
	}

	/**
	 * @testdox instantiate_graphql_controller returns a wired-up controller subclass.
	 */
	public function test_instantiate_returns_controller(): void {
		$controller = Main::instantiate_graphql_controller( DummyGraphQLController::class );

		$this->assertInstanceOf( GraphQLControllerBase::class, $controller );
	}

	/**
	 * @testdox register_graphql_endpoint rejects classes that are not GraphQLControllerBase subclasses.
	 */
	public function test_register_graphql_endpoint_rejects_unrelated_classes(): void {
		$this->expectException( \InvalidArgumentException::class );
		Main::register_graphql_endpoint( \stdClass::class, 'wc-test', '/bogus' );
	}

	/**
	 * @testdox register_graphql_endpoint rejects directories that don't contain a generated controller.
	 */
	public function test_register_graphql_endpoint_rejects_directory_without_controller(): void {
		$tmp = sys_get_temp_dir() . '/wc-graphql-no-controller-' . uniqid();
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_mkdir
		mkdir( $tmp, 0755, true );

		try {
			$this->expectException( \InvalidArgumentException::class );
			Main::register_graphql_endpoint( $tmp, 'wc-test', '/missing' );
		} finally {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir
			rmdir( $tmp );
		}
	}

	/**
	 * @testdox register hooks the OPcache cleanup handler onto its scheduled action.
	 */
	public function test_register_hooks_opcache_cleanup(): void {
		$callback = array( OpcacheFileExpiry::class, 'handle_cleanup_action' );
		remove_action( OpcacheFileExpiry::ACTION_HOOK, $callback );

		Main::register();

		$this->assertNotFalse(
			has_action( OpcacheFileExpiry::ACTION_HOOK, $callback ),
			'register() should hook handle_cleanup_action onto the OPcache cleanup action.'
		);
	}

	/**
	 * @testdox register also bootstraps Settings — its filter hooks become active.
	 */
	public function test_register_bootstraps_settings(): void {
		// Snapshot the existing hook state so unrelated callbacks attached
		// elsewhere in the test process aren't dropped by remove_all_filters().
		$saved_sections = $GLOBALS['wp_filter']['woocommerce_get_sections_advanced'] ?? null;
		$saved_settings = $GLOBALS['wp_filter']['woocommerce_get_settings_advanced'] ?? null;

		remove_all_filters( 'woocommerce_get_sections_advanced' );
		remove_all_filters( 'woocommerce_get_settings_advanced' );

		try {
			Main::register();

			$this->assertNotFalse( has_filter( 'woocommerce_get_sections_advanced' ) );
			$this->assertNotFalse( has_filter( 'woocommerce_get_settings_advanced' ) );
		} finally {
			// phpcs:disable WordPress.WP.GlobalVariablesOverride.Prohibited -- restoring the snapshot taken above.
			if ( null === $saved_sections ) {
				unset( $GLOBALS['wp_filter']['woocommerce_get_sections_advanced'] );
			} else {
				$GLOBALS['wp_filter']['woocommerce_get_sections_advanced'] = $saved_sections;
			}
			if ( null === $saved_settings ) {
				unset( $GLOBALS['wp_filter']['woocommerce_get_settings_advanced'] );
			} else {
				$GLOBALS['wp_filter']['woocommerce_get_settings_advanced'] = $saved_settings;
			}
			// phpcs:enable WordPress.WP.GlobalVariablesOverride.Prohibited
		}
	}

	/**
	 * @testdox resolve_controller_class returns its argument unchanged when given an FQCN.
	 */
	public function test_resolve_controller_class_passes_through_fqcn(): void {
		$reflection = new \ReflectionClass( Main::class );
		$method     = $reflection->getMethod( 'resolve_controller_class' );
		$method->setAccessible( true );

		$result = $method->invoke( null, 'Some\\Plugin\\GraphQLController' );

		$this->assertSame( 'Some\\Plugin\\GraphQLController', $result );
	}

	/**
	 * @testdox resolve_controller_class extracts the namespace from a generated controller file.
	 */
	public function test_resolve_controller_class_extracts_namespace_from_directory(): void {
		$tmp_root = sys_get_temp_dir() . '/wc-graphql-resolve-' . uniqid();
		$dir      = $tmp_root . '/src/Internal/Api/Autogenerated';
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_mkdir
		mkdir( $dir, 0755, true );
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents,WordPress.WP.AlternativeFunctions.file_put_contents_file_put_contents
		file_put_contents(
			$dir . '/GraphQLController.php',
			"<?php\nnamespace Some\\Plugin\\Internal\\Api\\Autogenerated;\nclass GraphQLController {}\n"
		);

		$reflection = new \ReflectionClass( Main::class );
		$method     = $reflection->getMethod( 'resolve_controller_class' );
		$method->setAccessible( true );

		try {
			$result = $method->invoke( null, $tmp_root );
			$this->assertSame( 'Some\\Plugin\\Internal\\Api\\Autogenerated\\GraphQLController', $result );
		} finally {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_unlink,WordPress.WP.AlternativeFunctions.unlink_unlink
			unlink( $dir . '/GraphQLController.php' );
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir
			rmdir( $dir );
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir
			rmdir( $tmp_root . '/src/Internal/Api' );
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir
			rmdir( $tmp_root . '/src/Internal' );
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir
			rmdir( $tmp_root . '/src' );
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir
			rmdir( $tmp_root );
		}
	}

	/**
	 * @testdox extract_namespace_from_php_source handles common PHP source forms.
	 *
	 * @dataProvider provider_php_source_forms
	 *
	 * @param string  $source   PHP source fragment.
	 * @param ?string $expected The expected extracted namespace, or null when none.
	 */
	public function test_extract_namespace_handles_various_source_forms( string $source, ?string $expected ): void {
		$reflection = new \ReflectionClass( Main::class );
		$method     = $reflection->getMethod( 'extract_namespace_from_php_source' );
		$method->setAccessible( true );

		$this->assertSame( $expected, $method->invoke( null, $source ) );
	}

	/**
	 * @return array<string, array{0: string, 1: ?string}>
	 */
	public function provider_php_source_forms(): array {
		return array(
			'standard multi-line'          => array(
				"<?php\n\nnamespace Foo\\Bar\\Baz;\n\nclass Quux {}\n",
				'Foo\\Bar\\Baz',
			),
			'single-line declaration'      => array(
				'<?php namespace Foo\\Bar; class Quux {}',
				'Foo\\Bar',
			),
			'declare(strict_types) before' => array(
				"<?php\ndeclare(strict_types=1);\nnamespace Foo\\Bar;\nclass Quux {}\n",
				'Foo\\Bar',
			),
			'no namespace declared'        => array(
				"<?php\nclass Quux {}\n",
				null,
			),
			'leading and trailing slashes' => array(
				"<?php\nnamespace \\Foo\\Bar\\;\nclass Quux {}\n",
				'Foo\\Bar',
			),
		);
	}
}
